# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-25 11:34
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0048_add_fields_to_store_host_aws_keys'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaderboarddata',
            name='error',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
